source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

pod 'EaseMobSDKFull'
pod 'SVProgressHUD'
pod 'JDStatusBarNotification'
pod 'SDWebImage','~> 3.7.2'
pod 'MWPhotoBrowser', '~> 2.1.2'


target  'weixin2.0' do
# pod 'Kiwi'
end
